_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
                - 55
            "4": 3.13.0
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
batch_size:
    value: 128
dropout:
    value: 0.5
epochs:
    value: 100
learning_rate:
    value: 0.001
